const TMDB_API_KEY = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJmMTZiYTQ0NDRjYWQ4ODdjZGY0ZDE1Yjk3MGZlNjlhYSIsIm5iZiI6MTc4NjY1NjM4NS43MDcsInN1YiI6IjZhN2UzNjgxMDYxNjdmYTY2ZmM3YWI2MCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.WLWycZ1zW98G_x0bs90UHsFljmrwpPKoPvZBrP9ho2o";
const API="https://api.themoviedb.org/3", IMG="https://image.tmdb.org/t/p/w780";
const ARCHIVE_KEY="afterDarkArchive", USER_KEY="afterDarkUser";
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const body=document.body, cursor=$(".cursor"), archiveTrack=$("#archiveTrack"), searchInput=$("#searchInput"), searchResults=$("#searchResults");
let films=loadArchive(), currentType="all", searchController=null, searchTimer=null;
let movieNight={type:"all",genre:"any",year:"any",country:"any",rating:0,exclude:false,result:null,busy:false};
let ratings=loadRatings();
const GENRES={drama:18,comedy:35,thriller:53,horror:27,crime:80,romance:10749,fantasy:14,"sci-fi":878,mystery:9648,documentary:99};
const COUNTRY_NAMES={US:"USA",GB:"UK",FR:"FRANCE",DE:"GERMANY",IT:"ITALY",ES:"SPAIN",JP:"JAPAN",KR:"SOUTH KOREA",CN:"CHINA",HK:"HONG KONG",TW:"TAIWAN",IN:"INDIA",CA:"CANADA",AU:"AUSTRALIA",RU:"RUSSIA",SE:"SWEDEN",NO:"NORWAY",DK:"DENMARK",FI:"FINLAND",NL:"NETHERLANDS",BE:"BELGIUM",CH:"SWITZERLAND",PL:"POLAND",CZ:"CZECH REPUBLIC",BR:"BRAZIL",MX:"MEXICO",AR:"ARGENTINA",IE:"IRELAND",TR:"TURKEY",TH:"THAILAND",ID:"INDONESIA",IR:"IRAN",IL:"ISRAEL"};
function loadArchive(){try{return JSON.parse(localStorage.getItem(ARCHIVE_KEY)||"[]").filter(Boolean)}catch{return []}}
function saveArchive(){localStorage.setItem(ARCHIVE_KEY,JSON.stringify(films))}
function loadRatings(){try{return JSON.parse(localStorage.getItem("afterDarkRatings")||"[]")}catch{return []}}
function saveRatings(){localStorage.setItem("afterDarkRatings",JSON.stringify(ratings))}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
function typeOf(x){if((x.genre_ids||[]).includes(16))return"animation";return x.media_type==="tv"||x.first_air_date?"series":"film"}
function titleOf(x){return x.title||x.name||"UNTITLED"}
function yearOf(x){return (x.release_date||x.first_air_date||"").slice(0,4)||"—"}
function posterOf(x){return x.poster_path?IMG+x.poster_path:""}
async function tmdb(path,params={},opts={}){const u=new URL(API+path);Object.entries(params).forEach(([k,v])=>v!==undefined&&v!==null&&v!==""&&u.searchParams.set(k,v));const r=await fetch(u,{signal:opts.signal,headers:{Authorization:`Bearer ${TMDB_API_KEY}`,accept:"application/json"}});if(!r.ok)throw new Error(`TMDB ${r.status}`);return r.json()}
function initCursor(){if(!cursor)return;let x=innerWidth/2,y=innerHeight/2,cx=x,cy=y;document.addEventListener("pointermove",e=>{x=e.clientX;y=e.clientY;cursor.classList.remove("is-hidden")},{passive:true});function frame(){cx+=(x-cx)*.18;cy+=(y-cy)*.18;cursor.style.setProperty("--cursor-x",cx+"px");cursor.style.setProperty("--cursor-y",cy+"px");const hit=document.elementFromPoint(x,y);cursor.classList.toggle("is-hover",!!hit?.closest("button,a,input,select,.archive-card,.search-result,.rating-card"));requestAnimationFrame(frame)}frame()}
function initIndex(){$(".index-trigger")?.addEventListener("click",()=>$(".index-panel")?.classList.add("active"));$(".index-close")?.addEventListener("click",()=>$(".index-panel")?.classList.remove("active"));$$('.index-nav a').forEach(a=>a.addEventListener("click",()=>$(".index-panel")?.classList.remove("active")))}
function updateArchiveCounters(n){const v=$("#visibleCount"),t=$("#totalCount"),a=$("#archiveCount");if(v)v.textContent=String(n).padStart(2,"0");if(t)t.textContent=String(films.length).padStart(2,"0");if(a)a.textContent=String(films.length).padStart(2,"0")}
function renderArchive(){if(!archiveTrack)return;const list=currentType==="all"?films:films.filter(f=>f.type===currentType);archiveTrack.innerHTML=list.length?list.map((f,i)=>`<article class="archive-card" data-id="${esc(f.tmdbId)}"><div class="archive-card-poster"><img src="${esc(posterOf(f))}" alt="${esc(titleOf(f))}" loading="lazy"><span>${String(i+1).padStart(2,"0")}</span></div><div class="archive-card-meta"><span>${esc(f.type?.toUpperCase()||"FILM")}</span><span>${esc(yearOf(f))}</span></div><h3>${esc(titleOf(f))}</h3><button class="archive-remove" data-action="remove" data-id="${esc(f.tmdbId)}" type="button">REMOVE ×</button></article>`).join(""): `<div class="archive-empty"><span>00</span><p>ARCHIVE IS EMPTY.</p><small>SEARCH FOR A TITLE ABOVE AND KEEP IT FOR LATER.</small></div>`;updateArchiveCounters(list.length)}
function addFilm(f){if(films.some(x=>Number(x.tmdbId)===Number(f.id)))return false;films.unshift({tmdbId:f.id,title:titleOf(f),name:f.name,poster_path:f.poster_path,backdrop_path:f.backdrop_path,release_date:f.release_date,first_air_date:f.first_air_date,type:typeOf(f),vote_average:f.vote_average,genre_ids:f.genre_ids||[],originCountries:f.origin_country||[]});saveArchive();renderArchive();return true}
function renderSearch(items){window.__searchResults=items;if(!searchResults)return;searchResults.innerHTML=items.length?`<div class="search-results-head"><span>RESULTS</span><span>${String(items.length).padStart(2,"0")}</span></div>`+items.map((f,i)=>{const inA=films.some(x=>Number(x.tmdbId)===Number(f.id));return `<article class="search-result" data-id="${esc(f.id)}"><span class="search-result-index">${String(i+1).padStart(2,"0")}</span><div class="search-result-poster">${f.poster_path?`<img src="${esc(posterOf(f))}" alt="${esc(titleOf(f))}" loading="lazy">`:"<span>NO<br>IMAGE</span>"}</div><div class="search-result-info"><h3>${esc(titleOf(f))}</h3><p>${esc(typeOf(f).toUpperCase())} · ${esc(yearOf(f))} · ★ ${Number(f.vote_average||0).toFixed(1)}</p></div><button class="search-result-add ${inA?"added":""}" type="button" data-action="add">${inA?"IN ARCHIVE":"ADD +"}</button></article>`}).join(""):""}
async function search(){const q=searchInput?.value.trim();if(!q){searchResults.innerHTML="";return}searchController?.abort();searchController=new AbortController();searchResults.innerHTML=`<div class="search-state">SEARCHING DATABASE<span></span></div>`;try{const data=await tmdb("/search/multi",{query:q,include_adult:"false",language:"en-US",page:1},{signal:searchController.signal});renderSearch((data.results||[]).filter(x=>["movie","tv"].includes(x.media_type)).slice(0,12))}catch(e){if(e.name!=="AbortError")searchResults.innerHTML=`<div class="search-state error">DATABASE CONNECTION FAILED</div>`}}
function initSearch(){$("#searchButton")?.addEventListener("click",search);searchInput?.addEventListener("keydown",e=>{if(e.key==="Enter")search()});searchInput?.addEventListener("input",()=>{clearTimeout(searchTimer);if(!searchInput.value.trim()){searchResults.innerHTML="";return}searchTimer=setTimeout(search,450)});searchResults?.addEventListener("click",e=>{const btn=e.target.closest("[data-action='add']");if(!btn)return;const row=btn.closest(".search-result"),item=window.__searchResults?.find(x=>Number(x.id)===Number(row?.dataset.id));if(item){addFilm(item);btn.textContent="IN ARCHIVE";btn.classList.add("added")}})}
function initArchive(){renderArchive();$$('.filter').forEach(b=>b.addEventListener("click",()=>{$$('.filter').forEach(x=>x.classList.remove("active"));b.classList.add("active");currentType=b.dataset.type||"all";renderArchive()}));archiveTrack?.addEventListener("click",e=>{const b=e.target.closest("[data-action='remove']");if(!b)return;films=films.filter(f=>Number(f.tmdbId)!==Number(b.dataset.id));saveArchive();renderArchive()});let drag=false,start=0,scroll=0;archiveTrack?.addEventListener("pointerdown",e=>{if(e.target.closest("button"))return;drag=true;start=e.clientX;scroll=archiveTrack.scrollLeft;archiveTrack.setPointerCapture(e.pointerId);archiveTrack.classList.add("is-dragging")});archiveTrack?.addEventListener("pointermove",e=>{if(!drag)return;archiveTrack.scrollLeft=scroll-(e.clientX-start)*1.15});["pointerup","pointercancel","lostpointercapture"].forEach(n=>archiveTrack?.addEventListener(n,()=>{drag=false;archiveTrack.classList.remove("is-dragging")}));$$('[data-carousel]').forEach(b=>b.addEventListener("click",()=>archiveTrack?.scrollBy({left:(b.dataset.carousel==="next"?1:-1)*Math.max(280,archiveTrack.clientWidth*.65),behavior:"smooth"})))}
function setChoice(attr,value){$$(`[${attr}]`).forEach(b=>b.classList.toggle("active",b.getAttribute(attr)===value))}
function initMovieNight(){const root=$("#movie-night");if(!root)return;$$('.movie-night-option[data-filter-type]').forEach(b=>b.addEventListener("click",()=>{movieNight.type=b.dataset.filterType;setChoice("data-filter-type",movieNight.type)}));$$('.movie-night-option[data-genre]').forEach(b=>b.addEventListener("click",()=>{movieNight.genre=b.dataset.genre;setChoice("data-genre",movieNight.genre)}));$$('.movie-night-option[data-year]').forEach(b=>b.addEventListener("click",()=>{movieNight.year=b.dataset.year;setChoice("data-year",movieNight.year)}));$$('.movie-night-option[data-rating]').forEach(b=>b.addEventListener("click",()=>{movieNight.rating=Number(b.dataset.rating);setChoice("data-rating",String(movieNight.rating))}));$("#movieNightCountry")?.addEventListener("change",e=>movieNight.country=e.target.value);$("#excludeArchive")?.addEventListener("change",e=>movieNight.exclude=e.target.checked);$("#decideButton")?.addEventListener("click",decideMovie);$("#movieNightModalBackdrop")?.addEventListener("click",closeMovieNight);$("#movieNightModalClose")?.addEventListener("click",closeMovieNight);$("#movieNightAdd")?.addEventListener("click",()=>{if(movieNight.result){addFilm(movieNight.result);updateMovieNightButtons()}});$("#movieNightOpen")?.addEventListener("click",closeMovieNight)}
function buildDiscoverParams(){const p={language:"en-US",page:Math.floor(Math.random()*8)+1,sort_by:"popularity.desc",include_adult:"false",vote_count_gte:20};if(movieNight.type==="series")p.with_type="tv";if(movieNight.genre!=="any")p.with_genres=GENRES[movieNight.genre];else if(movieNight.type==="animation")p.with_genres=16;if(movieNight.country!=="any")p.with_origin_country=movieNight.country;if(movieNight.rating)p["vote_average.gte"]=movieNight.rating;const y=movieNight.year;if(y==="before-1990"){p["primary_release_date.lte"]="1989-12-31";p["first_air_date.lte"]="1989-12-31"}else if(/^\d{4}-\d{4}$/.test(y)){const [a,b]=y.split("-");p["primary_release_date.gte"]=`${a}-01-01`;p["primary_release_date.lte"]=`${b}-12-31`}else if(y==="2020"){p["primary_release_date.gte"]="2020-01-01";p["first_air_date.gte"]="2020-01-01"}return p}
async function decideMovie(){if(movieNight.busy)return;movieNight.busy=true;const modal=$("#movieNightModal"),reveal=$("#movieNightReveal"),final=$("#movieNightFinal");modal?.classList.add("active");body.classList.add("movie-night-modal-open");reveal?.classList.remove("done");final?.classList.remove("visible");$("#movieNightRevealTrack")?.replaceChildren();let timer=null;try{let candidates=[];if(movieNight.type==="all"){const [m,t]=await Promise.all([tmdb("/discover/movie",buildDiscoverParams()),tmdb("/discover/tv",buildDiscoverParams())]);candidates=[...(m.results||[]),...(t.results||[])]}else{const d=await tmdb(movieNight.type==="series"?"/discover/tv":"/discover/movie",buildDiscoverParams());candidates=d.results||[]}candidates=candidates.filter(x=>x.poster_path&&(!movieNight.exclude||!films.some(f=>Number(f.tmdbId)===Number(x.id))));if(!candidates.length)throw new Error("NO TITLES MATCH THE FILTERS");const winner=candidates[Math.floor(Math.random()*candidates.length)];movieNight.result=winner;const track=$("#movieNightRevealTrack"),names=candidates.slice(0,10).map(titleOf);let i=0;timer=setInterval(()=>{if(track)track.innerHTML=`<span>${esc(names[i%names.length])}</span>`;i++},110);await new Promise(r=>setTimeout(r,2100));clearInterval(timer);timer=null;showMovieNightResult(winner);reveal?.classList.add("done");final?.classList.add("visible")}catch(e){clearInterval(timer);const track=$("#movieNightRevealTrack");if(track)track.innerHTML=`<span class="error">${esc(e.message||"NO MATCH")}</span>`;reveal?.classList.add("done")}finally{movieNight.busy=false}}
function showMovieNightResult(f){const p=$("#movieNightPoster"),ti=$("#movieNightTitle"),y=$("#movieNightYear"),r=$("#movieNightRating"),ty=$("#movieNightType"),sm=$("#movieNightSubmeta"),ov=$("#movieNightOverview"),st=$("#movieNightArchiveStatus");if(p){p.src=posterOf(f);p.alt=titleOf(f)}if(ti)ti.textContent=titleOf(f).toUpperCase();if(y)y.textContent=yearOf(f);if(r)r.textContent=`★ ${Number(f.vote_average||0).toFixed(1)}`;if(ty)ty.textContent=typeOf(f).toUpperCase();if(sm)sm.textContent=`${(f.origin_country||[]).map(c=>COUNTRY_NAMES[c]||c).join(" / ")||"TMDB"}`;if(ov)ov.textContent=f.overview||"No description available.";if(st)st.textContent=films.some(x=>Number(x.tmdbId)===Number(f.id))?"ALREADY IN ARCHIVE":"FROM TMDB";updateMovieNightButtons()}
function updateMovieNightButtons(){const b=$("#movieNightAdd");if(!b||!movieNight.result)return;const inA=films.some(x=>Number(x.tmdbId)===Number(movieNight.result.id));b.textContent=inA?"IN ARCHIVE":"ADD TO ARCHIVE";b.disabled=inA}
function closeMovieNight(){$("#movieNightModal")?.classList.remove("active");body.classList.remove("movie-night-modal-open");movieNight.result=null}
function initRatings(){const list=$("#ratingsList");if(!list)return;renderRatings();document.addEventListener("click",e=>{const b=e.target.closest("[data-rating-delete]");if(!b)return;ratings=ratings.filter(r=>r.id!==b.dataset.ratingDelete);saveRatings();renderRatings()})}
function renderRatings(){const list=$("#ratingsList");if(!list)return;const base=ratings.length?ratings:[{id:"demo1",title:"THE GODFATHER",type:"FILM",year:1972,polina:9.5,nastya:9.2},{id:"demo2",title:"BLACK SWAN",type:"FILM",year:2010,polina:9.1,nastya:9.4},{id:"demo3",title:"DARK",type:"SERIES",year:2017,polina:9.4,nastya:8.9}];list.innerHTML=base.map(r=>`<article class="rating-card"><div class="rating-card-top"><span>${esc(r.type)}</span><span>${esc(r.year)}</span></div><h3>${esc(r.title)}</h3><div class="rating-duo"><div><small>POLINA</small><strong>${Number(r.polina).toFixed(1)}</strong></div><div><small>NASTYA</small><strong>${Number(r.nastya).toFixed(1)}</strong></div></div><div class="rating-average">AVERAGE <b>${((Number(r.polina)+Number(r.nastya))/2).toFixed(1)}</b></div>${String(r.id).startsWith("demo")?"":`<button type="button" data-rating-delete="${esc(r.id)}">REMOVE ×</button>`}</article>`).join("")}
function initAuth(){const modal=$("#authModal"),open=$("#authButton"),close=$("#authClose");if(!modal)return;const panel=modal.querySelector(".auth-modal-window,.auth-window")||modal.firstElementChild;if(panel){panel.innerHTML=`<button class="auth-close" id="authLocalClose" type="button">×</button><div class="auth-kicker">PRIVATE CINEMA</div><h2>WELCOME<br><em>BACK.</em></h2><div class="auth-tabs"><button class="active" data-auth-mode="login" type="button">SIGN IN</button><button data-auth-mode="register" type="button">REGISTER</button></div><form id="authLocalForm"><label>NAME<input id="authLocalName" autocomplete="name" placeholder="your name"></label><label>EMAIL<input id="authLocalEmail" type="email" required autocomplete="email" placeholder="you@example.com"></label><label>PASSWORD<input id="authLocalPassword" type="password" required minlength="6" autocomplete="current-password" placeholder="••••••••"></label><button type="submit" class="auth-submit">CONTINUE ↗</button><p class="auth-note">For this private archive, the demo account is stored locally in this browser.</p></form>`}function closeIt(){modal.classList.remove("active");modal.setAttribute("aria-hidden","true")}open?.addEventListener("click",()=>{modal.classList.add("active");modal.setAttribute("aria-hidden","false")});close?.addEventListener("click",closeIt);$("#authLocalClose")?.addEventListener("click",closeIt);modal.addEventListener("click",e=>{if(e.target===modal)closeIt()});$$('[data-auth-mode]',modal).forEach(b=>b.addEventListener("click",()=>{$$('[data-auth-mode]',modal).forEach(x=>x.classList.remove("active"));b.classList.add("active");const reg=b.dataset.authMode==="register";$("#authLocalName",modal).closest("label").style.display=reg?"grid":"none";$("#authLocalForm",modal).dataset.mode=reg?"register":"login"}));$("#authLocalForm")?.addEventListener("submit",e=>{e.preventDefault();const form=e.currentTarget,mode=form.dataset.mode||"login",email=$("#authLocalEmail").value.trim().toLowerCase(),password=$("#authLocalPassword").value,user=JSON.parse(localStorage.getItem(USER_KEY)||"null");if(mode==="register"){localStorage.setItem(USER_KEY,JSON.stringify({name:$("#authLocalName").value.trim()||"Cinema user",email,password}));closeIt();return}if(!user||user.email!==email||user.password!==password){alert("No matching local account. Register first.");return}closeIt()})}
function init(){initCursor();initIndex();initSearch();initArchive();initMovieNight();initRatings();initAuth()}
init();